platform :ios, '12.0'

def available_pod
  pod 'Stickers', :path => '../..'    
end

def ui
  pod 'IDPRootViewGettable', :git => 'https://github.com/idapgroup/IDPRootViewGettable.git', :commit => '4cd3852'
  pod 'SnapKit',                '~> 5.0.0'
end

target 'SampleStickersApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleStickersApp
  available_pod
  ui
end
