platform :ios, '12.0'

def available_pod
  pod 'Stickers', :path => '../..'    
end

target 'SampleStickersApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleStickersApp
  available_pod
end
